#pragma once

enum JOB_INDEX {WARRIOR , WIZARD , THIEF};
enum TEXTURE_ID {TEXTURE_SINGLE , TEXTURE_MULTI, TEXTURE_END};
enum SCENE_ID {LOADING, STAGE, SCENE_END};
enum WINDOW_MODE{MODE_FULL, MODE_WINDOW};
enum OBJECT_ID { TERRAIN, OBEJCT, PLAYER, MONSTER, BOSS, UI, OBJECT_END };