#pragma once

enum JOB_INDEX {WARRIOR , WIZARD , THIEF};
enum TEXTURE_ID {TEXTURE_SINGLE , TEXTURE_MULTI, TEXTURE_END};
enum SCENE_ID {LOADING, STAGE,MONSTER_SCENE1, MONSTER_SCENE2,BOSS_SCENE, SCENE_END};
enum WINDOW_MODE{MODE_FULL, MODE_WINDOW};
enum OBJECT_ID { RESPAWN_TILE, SCENE_TILE, OBEJCT, ITEM, USING_ITEM ,WATERBALL, WATER, PLAYER, MONSTER, BOSS, UI, OBJECT_END };
enum SCENE_OBJECT_ID{TILE=1,BOX,WALL};
enum CHARACTER_STATE { STAND, WALK_LEFT, WALK_RIGHT, WALK_UP, WALK_DOWN, TRAPPED,REVIVAL, DIE, HIT, WIN };

enum RENDER_ID {RENDER_TILE, RENDER_OBJECT, REDNER_UI,RENDER_END};